version: '2'

services:

  web:
    image: node
    volumes:
      - .:/app
    ports:
      - '8089:8088'
      - '5859:5858'
    working_dir: /app
    command: npm run serve
    environment:
      NODE_ENV: development
      PORT: 8088
